db-scheduler:
  enabled: true
  table-name: scheduled_tasks
  polling-strategy: lock_and_fetch
  threads: 10m
  polling-strategy-lower-limit-fraction-of-threads: '0.5'
  polling-strategy-upper-limit-fraction-of-threads: '3.0'
  heartbeat-interval: 5m
  shutdown-max-wait: 10m
  polling-interval: 10m
  delay-startup-until-context-ready: true
  immediate-execution-enabled: false

